site_name: The Bash Hackers Wiki
site_url: https://flokoe.github.io/bash-hackers-wiki/

repo_url: https://github.com/flokoe/bash-hackers-wiki
repo_name: flokoe/bash-hackers-wiki
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.action.view
    - content.action.edit
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
  - awesome-pages
  - tags:
      tags_file: tags.md
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true

markdown_extensions:
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - footnotes
  - toc:
      permalink: true

nav:
  - Start: index.md
  - ... | regex=^(?!need_love\.md|bash4\.md|wishes\.md|tags\.md)
  - tags.md

watch:
  - overrides
